version: '3.9'

services:

  lavalink:
    container_name: lavalink
    build:
      dockerfile: ./cmd/lavalink-service/Dockerfile
    restart: unless-stopped
    networks:
      - lavalink

  azteradio:
    container_name: radio-service
    env_file:
      ./cmd/radio-service/.env
    build:
      dockerfile: ./cmd/radio-service/Dockerfile
    volumes: 
      - "./logs/radio-service:/app/logs"
    networks:
      - lavalink
  

networks:
  # create a lavalink network you can add other containers to, to give them access to Lavalink
  lavalink:
    name: lavalink