version: '3.9'

services:

  lavalink:
    container_name: lavalink
    build:
      dockerfile: ./cmd/lavalink-service/Dockerfile
    restart: unless-stopped
    networks:
      - lavalink

  azteradio:
    container_name: radio-service
    env_file:
      ./cmd/radio-service/.env
    build:
      dockerfile: ./cmd/radio-service/Dockerfile
    volumes: 
      - "./logs/radio-service:/app/logs"
    networks:
      - lavalink

  aztemusic-1:
    container_name: music-service-1
    env_file:
      ./cmd/music-service/1/.env
    build:
      dockerfile: ./cmd/music-service/1/Dockerfile
    volumes: 
      - "./logs/music-service/1:/app/logs"
    networks:
      - lavalink

  aztemusic-2:
    container_name: music-service-2
    env_file:
      ./cmd/music-service/2/.env
    build:
      dockerfile: ./cmd/music-service/2/Dockerfile
    volumes: 
      - "./logs/music-service/2:/app/logs"
    networks:
      - lavalink
  

networks:
  # create a lavalink network you can add other containers to, to give them access to Lavalink
  lavalink:
    name: lavalink