version: '3.9'

services:

  aztemusic:
    container_name: music-service
    env_file:
      ./cmd/music-service/.env
    build:
      dockerfile: ./cmd/music-service/Dockerfile
    volumes: 
      - "./logs/music-service:/app/logs"