version: '3.9'

services:

  lavalink:
    container_name: lavalink
    build:
      dockerfile: ./cmd/lavalink-service/Dockerfile
    restart: unless-stopped
    networks:
      - lavalink

  aztemusic:
    container_name: music-service
    env_file:
      ./cmd/music-service/.env
    build:
      dockerfile: ./cmd/music-service/Dockerfile
    volumes: 
      - "./logs/music-service:/app/logs"
    networks:
      - lavalink
  

networks:
  # create a lavalink network you can add other containers to, to give them access to Lavalink
  lavalink:
    name: lavalink