# This workflow is ran only on pushes to main. It builds the project artifact and deploys it to Google Cloud Compute Engine.
# It also generates releases and tags the commits.

name: deploy

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'README.md'
      - '.gitignore'
      - '.gitmodules'
      - 'Makefile'
    branches: [ 'main' ]

  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  DOCKER_ARTIFACT_REPOSITORY: ${{ secrets.GCE_PROJECT_DOCKER_ARTIFACT_REGISTRY }} # TODO: Try and make this follow the instance zone declared in the infrastructure repo ?
  GKE_ZONE: europe-west2-c # TODO: Try and make this follow the instance zone declared in the infrastructure repo ?
  GKE_REGION: europe-west2 # TODO: Try and make this follow the instance zone declared in the infrastructure repo ?
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  AZTEBOT_IMAGE: aztebot-service
  # TODO: These will be removed from this deployment pipeline once the Go version of AzteMusic is released
  AZTERADIO_IMAGE: azteradio-service
  AZTEMUSIC_IMAGE_1: aztemusic-service-1
  AZTEMUSIC_IMAGE_2: aztemusic-service-2
  AZTEMUSIC_IMAGE_3: aztemusic-service-3

jobs:

  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - name: Generate next release number
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          dry_run: true

      - name: Setup environment
        run: |
          : # Environment variables for AzteBot
          echo ${{ secrets.ENV_BASE64_STRING }} | base64 --decode > .env

          : # Environment variables for AzteMusic services (in Golang)
          : # INACTIVE FOR NOW
          : # echo ${{ secrets.AZTERADIO_ENV_BASE64 }} | base64 --decode > cmd/azteradio-service/config.yml
          : # echo ${{ secrets.AZTEMUSIC_1_ENV_BASE64 }} | base64 --decode > cmd/aztemusic-service/1/config.yml

          : # Environment variables for AzteMusic services (in Java)
          echo ${{ secrets.JAR_AZTERADIO_CONFIG }} | base64 --decode > cmd/aztemusic-service-jar/azteradio-service/config.txt
          echo ${{ secrets.JAR_AZTEMUSIC_1_CONFIG }} | base64 --decode > cmd/aztemusic-service-jar/aztemusic-service-1/config.txt
          echo ${{ secrets.JAR_AZTEMUSIC_2_CONFIG }} | base64 --decode > cmd/aztemusic-service-jar/aztemusic-service-2/config.txt
          echo ${{ secrets.JAR_AZTEMUSIC_3_CONFIG }} | base64 --decode > cmd/aztemusic-service-jar/aztemusic-service-3/config.txt

      - name: Generate SHA output
        id: vars
        run: echo "GITHUB_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_GITHUB_WIP }}
          service_account: ${{ secrets.GCP_GITHUB_SERVICE_ACCOUNT }}
          access_token_lifetime: '240s'
      
      - uses: 'docker/login-action@v1'
        name: 'Docker login'
        with:
          registry: '${{ env.GKE_REGION }}-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: 'Docker build'
        run: |
          docker build --tag "${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.AZTEBOT_IMAGE }}:${{ steps.vars.outputs.GITHUB_SHA }}" -f cmd/bot-service/Dockerfile .

          docker build --tag "${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.AZTERADIO_IMAGE }}:${{ steps.vars.outputs.GITHUB_SHA }}" -f cmd/aztemusic-service-jar/azteradio-service/Dockerfile .

          docker build --tag "${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.AZTEMUSIC_IMAGE_1 }}:${{ steps.vars.outputs.GITHUB_SHA }}" -f cmd/aztemusic-service-jar/aztemusic-service-1/Dockerfile .
          docker build --tag "${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.AZTEMUSIC_IMAGE_2 }}:${{ steps.vars.outputs.GITHUB_SHA }}" -f cmd/aztemusic-service-jar/aztemusic-service-2/Dockerfile .
          docker build --tag "${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.AZTEMUSIC_IMAGE_3 }}:${{ steps.vars.outputs.GITHUB_SHA }}" -f cmd/aztemusic-service-jar/aztemusic-service-3/Dockerfile .

      - name: 'Docker push'
        run: |
          docker push "${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.AZTEBOT_IMAGE }}:${{ steps.vars.outputs.GITHUB_SHA }}"

          docker push "${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.AZTERADIO_IMAGE }}:${{ steps.vars.outputs.GITHUB_SHA }}"

          docker push "${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.AZTEMUSIC_IMAGE_1 }}:${{ steps.vars.outputs.GITHUB_SHA }}"
          docker push "${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.AZTEMUSIC_IMAGE_2 }}:${{ steps.vars.outputs.GITHUB_SHA }}"
          docker push "${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.AZTEMUSIC_IMAGE_3 }}:${{ steps.vars.outputs.GITHUB_SHA }}"
      
      - name: Connect to GKE
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.GKE_ZONE }}
      
      - name: Export deployment variables
        run: |
          export GCE_PROJECT="${{ env.PROJECT_ID }}"
          export GCE_PROJECT_DOCKER_ARTIFACT_REGISTRY="${{ env.DOCKER_ARTIFACT_REPOSITORY }}"
      
      - name: Remove previous deployments
        run: |
          kubectl delete deployment --ignore-not-found=true aztebot-service-${{ steps.tag_version.outputs.previous_tag }}

          kubectl delete deployment --ignore-not-found=true azteradio-service-${{ steps.tag_version.outputs.previous_tag }}

          kubectl delete deployment --ignore-not-found=true aztemusic-service-1-${{ steps.tag_version.outputs.previous_tag }}
          kubectl delete deployment --ignore-not-found=true aztemusic-service-2-${{ steps.tag_version.outputs.previous_tag }}
          kubectl delete deployment --ignore-not-found=true aztemusic-service-3-${{ steps.tag_version.outputs.previous_tag }}
      
      - name: Create GKE Deployments for new image
        run: |
          kubectl create deployment aztebot-service-${{ steps.tag_version.outputs.new_tag }} --image="${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.AZTEBOT_IMAGE }}:${{ steps.vars.outputs.GITHUB_SHA }}"

          kubectl create deployment azteradio-service-${{ steps.tag_version.outputs.new_tag }} --image="${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.AZTERADIO_IMAGE }}:${{ steps.vars.outputs.GITHUB_SHA }}"

          kubectl create deployment aztemusic-service-1-${{ steps.tag_version.outputs.new_tag }} --image="${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.AZTEMUSIC_IMAGE_1 }}:${{ steps.vars.outputs.GITHUB_SHA }}"
          kubectl create deployment aztemusic-service-2-${{ steps.tag_version.outputs.new_tag }} --image="${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.AZTEMUSIC_IMAGE_2 }}:${{ steps.vars.outputs.GITHUB_SHA }}"
          kubectl create deployment aztemusic-service-3-${{ steps.tag_version.outputs.new_tag }} --image="${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.AZTEMUSIC_IMAGE_3 }}:${{ steps.vars.outputs.GITHUB_SHA }}"

      - name: Scale deployments
        run: |
          kubectl scale --replicas=1 deployment/aztebot-service-${{ steps.tag_version.outputs.new_tag }}

          kubectl scale --replicas=1 deployment/azteradio-service-${{ steps.tag_version.outputs.new_tag }}

          kubectl scale --replicas=1 deployment/aztemusic-service-1-${{ steps.tag_version.outputs.new_tag }}
          kubectl scale --replicas=1 deployment/aztemusic-service-2-${{ steps.tag_version.outputs.new_tag }}
          kubectl scale --replicas=1 deployment/aztemusic-service-3-${{ steps.tag_version.outputs.new_tag }}

      - name: Show created Pods
        run: |
          kubectl get pods
      
      - name: Create a new GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      