# This workflow is ran only on pushes to main. It builds the project artifact and deploys it to Google Cloud Compute Engine.
# It also generates releases and tags the commits.

name: deploy-lavalink

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'README.md'
      - '.gitignore'
      - '.dockerignore'
      - '.gitmodules'
      - 'docker-compose.yml'
      - 'Makefile'
      - 'cmd/music-service/**'
      - 'cmd/radio-service/**'
      - 'internal/bot/**'
      - 'internal/utils/**'
      - 'go.sum'
      - 'go.mod'
    branches: [ 'main' ]

  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  DOCKER_ARTIFACT_REPOSITORY: ${{ secrets.GCE_PROJECT_DOCKER_ARTIFACT_REGISTRY }} # TODO: Try and make this follow the instance zone declared in the infrastructure repo ?
  GKE_ZONE: europe-west2-c # TODO: Try and make this follow the instance zone declared in the infrastructure repo ?
  GKE_REGION: europe-west2 # TODO: Try and make this follow the instance zone declared in the infrastructure repo ?
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  LAVALINK_IMAGE: lavalink-service

jobs:

  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          : # Configuration file for LavaLink server
          echo ${{ secrets.LAVALINK_CONFIG_BASE64 }} | base64 --decode > internal/lavalink/application.yml

      - name: Generate SHA output
        id: vars
        run: echo "GITHUB_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_GITHUB_WIP }}
          service_account: ${{ secrets.GCP_GITHUB_SERVICE_ACCOUNT }}
          access_token_lifetime: '240s'
      
      - uses: 'docker/login-action@v1'
        name: 'Docker login'
        with:
          registry: '${{ env.GKE_REGION }}-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: 'Docker build'
        run: |
          docker build --tag "${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.LAVALINK_IMAGE }}:${{ steps.vars.outputs.GITHUB_SHA }}" -f cmd/lavalink-service/Dockerfile .

      - name: 'Docker push'
        run: |
          docker push "${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.LAVALINK_IMAGE }}:${{ steps.vars.outputs.GITHUB_SHA }}"
      
      - name: Connect to GKE
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.GKE_ZONE }}
      
      - name: Export deployment variables
        run: |
          export GCE_PROJECT="${{ env.PROJECT_ID }}"
          export GCE_PROJECT_DOCKER_ARTIFACT_REGISTRY="${{ env.DOCKER_ARTIFACT_REPOSITORY }}"
      
      - name: Remove previous deployments
        run: |
          kubectl delete deployment --ignore-not-found=true lavalink-service
          kubectl delete service --ignore-not-found=true lavalink-service
      
      - name: Create GKE Deployments for new image
        run: |
          kubectl create deployment lavalink-service --image="${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.DOCKER_ARTIFACT_REPOSITORY }}/${{ env.LAVALINK_IMAGE }}:${{ steps.vars.outputs.GITHUB_SHA }}"

      - name: Scale deployments
        run: |
          kubectl scale --replicas=1 deployment/lavalink-service
      
      - name: Expose deployments
        run: |
          kubectl expose deployment/lavalink-service --type="LoadBalancer" --port=2333 --target-port=2333 --name=${{ env.LAVALINK_IMAGE }}

      - name: Show created Pods
        run: |
          kubectl get pods
      